import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
const poppins = Poppins({
  variable: "poppins",
  subsets: ["latin"],
  weight:'500'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body
          className={`${poppins.className} antialiased`}
        >
          {children}
          <Toaster position="top-right"/>
        </body>
      </html>
  );
}
